### ISSUE TITLE
Getting error during build process on Vercel (`[next-plugin-preval] Error...`)

### ISSUE THREAD

**Issue by coheia** [ricokahler/next-plugin-preval#104]
The app was working normally, I haven't deployed it for about 4 months, so I had to do an update and when I went up, the build process broke. And I'm already freaking out here trying to find out why but the only clue I have is this log that the build process generated. If anyone out there can point me in some direction or any other help, it would be most welcome. Thanks in advance!

![image](https://user-images.githubusercontent.com/81380764/192874021-b67099ea-da98-41bc-a0d9-7cdca84bba7f.png)

**Comment by akshitkrnagpal** [comment]
@coheia Were you able to figure out why it was happening? I have the same error on my project.
