### ISSUE TITLE
Turbo monorepo next-plugin-preval response always cached 

### ISSUE THREAD

**Issue by pierremouchan** [ricokahler/next-plugin-preval#109]
Hello there,

Here is my tech stack:
- NextJS
- next-plugin-preval
- Turbo
- Vercel
- Prismic

I am working in a monorepo context and facing an issue with the cache of next-plugin-preval. I am using Prismic as a CMS, and when the client hits the deploy button, Vercel rebuilds the website and uses the Turbo cache if needed, which is what I want.

However, the problem I'm facing is that the preval data is cached by Turbo and not detected as a change when we update its data.

Has anyone faced this issue before, and does anyone know of any workarounds?

**Comment by dsacramone** [comment]
@pierremouchan You find a solution to this?

**Comment by pierremouchan** [comment]
> @pierremouchan You find a solution to this?

Outdated. I don't think this issue is relevant anymore and I don't think I found a solution to this in 2023.
