### ISSUE TITLE
Provide built-in fetch globally

### ISSUE THREAD

**Issue by ricokahler** [ricokahler/next-plugin-preval#12]
One inconsistency I've noticed is that [Next.js will provide a global fetch function in Node environments](https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support). Right now `next-plugin-preval` does not do that and it should!

**Comment by Vadorequest** [comment]
FYI here is how I fixed this in Next Right Now, I had a similar issue in Jest tests:

```ts
/**
 * Importing next during test applies automated polyfills:
 *  - Polyfill the built-in "fetch" provided by Next.js
 *
 * @see https://github.com/vercel/next.js/discussions/13678#discussioncomment-22383 How to use built-in fetch in tests?
 * @see https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support Next.js Blog - Improved Built-in Fetch Support
 * @see https://jestjs.io/docs/en/configuration#setupfilesafterenv-array About setupFilesAfterEnv usage
 */
require('next');
```

See https://github.com/UnlyEd/next-right-now/blob/30d83e961b6267ee7704d21b70004ee167f95ff5/jest.setup.js#L7-L15

**Comment by Vadorequest** [comment]
Awesome, I wasn't sure it would be that easy! Glad it is ;)
