### ISSUE TITLE
Webpack not using jsconfig.json aliases

### ISSUE THREAD

**Issue by fabien** [ricokahler/next-plugin-preval#44]
I'm trying to use the aliases defined in in `jsconfig.json` but unfortunately Preval does not pick them up:

```
[next-plugin-preval] Error: Cannot find module '@app/sanity/types'
```

My `jsconfig.json` :

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@app/*": ["./src/*"]
  },
  "exclude": ["node_modules"]
}
```

**Comment by ricokahler** [comment]
Ah, I think this is actually because the upstream package I use to support ts/jsconfig aliases doesn't support `jsconfig.json` yet.

https://github.com/dividab/tsconfig-paths/issues/127

Maybe try changing it to a `tsconfig.json` for now and then turn on `allowJs: true`?

**Comment by fabien** [comment]
Ah, I see. Will try that later, thanks!

**Comment by fabien** [comment]
> Maybe try changing it to a tsconfig.json for now and then turn on allowJs: true?

Follow-up: this works fine!
